//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version:2.0.40426.20
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.40426.20.
// 
namespace TestHarnessCS.AWWebService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AWProductionSoap", Namespace="http://AdventureWorks/")]
    public class AWProduction : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public AWProduction() {
            string urlSetting = System.Configuration.ConfigurationSettings.AppSettings["TestHarnessCS.AWWebService.AWProduction"];
            if ((urlSetting != null)) {
                this.Url = string.Concat(urlSetting, "");
            }
            else {
                this.Url = "http://localhost/AdventureWorks/Production";
            }
            this.ConformanceClaims = System.Web.Services.WsiClaims.BP10;
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://AdventureWorks/GetProducts", RequestNamespace="http://AdventureWorks/", ResponseNamespace="http://AdventureWorks/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetProducts() {
            object[] results = this.Invoke("GetProducts", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetProducts(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetProducts", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetProducts(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
    }
}
