//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50215.44
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data;
using System.Data.SqlTypes;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50215.44.
// 


/// <remarks/>
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="PersonEndpoint", Namespace="www.inhousebriefings.com")]
public partial class AdventureWorksTestEndpoint : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback s0MsgGetHighestPriceSoapInOperationCompleted;
    
    /// <remarks/>
    public AdventureWorksTestEndpoint() {
        this.Url = "http://localhost:8988/AdvTest";
    }
    
    /// <remarks/>
    public event s0MsgGetHighestPriceSoapInCompletedEventHandler s0MsgGetHighestPriceSoapInCompleted;
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute(MessageName="s0MsgGetHighestPriceSoapIn")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.inhousebriefings.comGetHighestPrice", RequestElementName="GetHighestPrice", RequestNamespace="www.inhousebriefings.com", ResponseElementName="GetHighestPriceResponse", ResponseNamespace="www.inhousebriefings.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("GetHighestPriceResult", IsNullable=true)]
    public System.Data.SqlTypes.SqlMoney GetHighestPrice([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Data.SqlTypes.SqlString CategoryName) {
        object[] results = this.Invoke("s0MsgGetHighestPriceSoapIn", new object[] {
                    CategoryName});
        return ((System.Data.SqlTypes.SqlMoney)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Begins0MsgGetHighestPriceSoapIn(System.Data.SqlTypes.SqlString CategoryName, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("s0MsgGetHighestPriceSoapIn", new object[] {
                    CategoryName}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.SqlTypes.SqlMoney Ends0MsgGetHighestPriceSoapIn(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.SqlTypes.SqlMoney)(results[0]));
    }
    
    /// <remarks/>
    public void s0MsgGetHighestPriceSoapInAsync(System.Data.SqlTypes.SqlString CategoryName) {
        this.s0MsgGetHighestPriceSoapInAsync(CategoryName, null);
    }
    
    /// <remarks/>
    public void s0MsgGetHighestPriceSoapInAsync(System.Data.SqlTypes.SqlString CategoryName, object userState) {
        if ((this.s0MsgGetHighestPriceSoapInOperationCompleted == null)) {
            this.s0MsgGetHighestPriceSoapInOperationCompleted = new System.Threading.SendOrPostCallback(this.Ons0MsgGetHighestPriceSoapInOperationCompleted);
        }
        this.InvokeAsync("s0MsgGetHighestPriceSoapIn", new object[] {
                    CategoryName}, this.s0MsgGetHighestPriceSoapInOperationCompleted, userState);
    }
    
    private void Ons0MsgGetHighestPriceSoapInOperationCompleted(object arg) {
        if ((this.s0MsgGetHighestPriceSoapInCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.s0MsgGetHighestPriceSoapInCompleted(this, new s0MsgGetHighestPriceSoapInCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
public delegate void s0MsgGetHighestPriceSoapInCompletedEventHandler(object sender, s0MsgGetHighestPriceSoapInCompletedEventArgs e);

/// <remarks/>
public partial class s0MsgGetHighestPriceSoapInCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal s0MsgGetHighestPriceSoapInCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.SqlTypes.SqlMoney Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.SqlTypes.SqlMoney)(this.results[0]));
        }
    }
}
