//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version:2.0.40426.20
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.40426.20.
// 
namespace WebServiceClient.sql_endpoint {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AWProductionSoap", Namespace="http://AdventureWorks/")]
    public class AWProduction : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public AWProduction() {
            string urlSetting = System.Configuration.ConfigurationSettings.AppSettings["WebServiceClient.sql_endpoint.AWProduction"];
            if ((urlSetting != null)) {
                this.Url = string.Concat(urlSetting, "");
            }
            else {
                this.Url = "http://localhost/AdventureWorks/Production";
            }
            this.ConformanceClaims = System.Web.Services.WsiClaims.BP10;
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://AdventureWorks/GetProducts", RequestNamespace="http://AdventureWorks/", ResponseNamespace="http://AdventureWorks/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetProducts() {
            object[] results = this.Invoke("GetProducts", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetProducts(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetProducts", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetProducts(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://AdventureWorks/UpdateProductPrice", RequestNamespace="http://AdventureWorks/", ResponseNamespace="http://AdventureWorks/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("SqlResultCode", typeof(int), Namespace="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlResultStream", IsNullable=false)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(typeof(SqlTransaction), Namespace="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlResultStream", IsNullable=false)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(typeof(SqlRowCount), Namespace="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlResultStream", IsNullable=false)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("SqlXml", typeof(System.Xml.XmlNode), Namespace="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlResultStream", IsNullable=false)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(typeof(SqlMessage), Namespace="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlResultStream", IsNullable=false)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("SqlRowSet", typeof(System.Data.DataSet), Namespace="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlResultStream", IsNullable=false)]
        public object[] UpdateProductPrice([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> ProductID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.Decimal> NewPrice) {
            object[] results = this.Invoke("UpdateProductPrice", new object[] {
                        ProductID,
                        NewPrice});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateProductPrice(System.Nullable<int> ProductID, System.Nullable<System.Decimal> NewPrice, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateProductPrice", new object[] {
                        ProductID,
                        NewPrice}, callback, asyncState);
        }
        
        /// <remarks/>
        public object[] EndUpdateProductPrice(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlTransaction")]
    public class SqlTransaction {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Descriptor;
        
        /// <remarks/>
        public SqlTransactionType Type;
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlTransaction")]
    public enum SqlTransactionType {
        
        /// <remarks/>
        Begin,
        
        /// <remarks/>
        Commit,
        
        /// <remarks/>
        Rollback,
        
        /// <remarks/>
        EnlistDTC,
        
        /// <remarks/>
        Defect,
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlRowCount")]
    public class SqlRowCount {
        
        /// <remarks/>
        public long Count;
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlMessage")]
    public class SqlMessage {
        
        /// <remarks/>
        public int Class;
        
        /// <remarks/>
        public int LineNumber;
        
        /// <remarks/>
        public string Message;
        
        /// <remarks/>
        public int Number;
        
        /// <remarks/>
        public string Procedure;
        
        /// <remarks/>
        public string Server;
        
        /// <remarks/>
        public string Source;
        
        /// <remarks/>
        public int State;
    }
}
